version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    volumes:
      - ./mosquitto:/mosquitto/
      - ./mosquitto/config:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001
  next-app:
    build: ./next-app
    container_name: next-app
    ports:
      - 3000:3000
    depends_on:
      - mosquitto
